RecipesProject/ViewModels/ErrorViewModel.cs
namespace RecipesProject.ViewModels
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RecipesProject/ViewModels/Recipes/CreateCategoryInputModel.cs
using System.ComponentModel.DataAnnotations;

namespace RecipesProject.ViewModels.Recipes
{
    public class CreateCategoryInputModel
    {
        public string CategoryName { get; set; }
    }
}

RecipesProject/ViewModels/Recipes/CreateRecipeInputModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace RecipesProject.ViewModels.Recipes
{
    public class CreateRecipeInputModel
    {
        [Required]
        [MinLength(4)]
        public string Title { get; set; }

        [Required]
        [MinLength(20)]
        public string Description { get; set; }

        [Range(0, 24 * 60)]
        [Display(Name = "Preparation time (in minutes)")]
        public int PreparationTime { get; set; }

        [Range(0, 24 * 60)]
        [Display(Name = "Cooking time (in minutes)")]
        public int CookingTime { get; set; }

        [Range(1, 100)]
        public int PortionsCount { get; set; }

        [Display(Name = "Choose Category")]
        public int CategoryId { get; set; }

        public IEnumerable<IFormFile> Photo { get; set; }
    
        public IEnumerable<RecipeIngredientInputModel> Ingredients { get; set; }

        public IEnumerable<SelectListItem> CategoriesItems { get; set; }
    }
}

RecipesProject/ViewModels/Recipes/IndexPageRecipeViewModel.cs
namespace RecipesProject.ViewModels.Recipes
{
    public class IndexPageRecipeViewModel
    {
        public int Id { get; set; }
        
        public IEnumerable<IndexRecipeViewModel> RecipeModel { get; set; }
    }
}

RecipesProject/ViewModels/Recipes/IndexRecipeViewModel.cs
namespace RecipesProject.ViewModels.Recipes
{
    public class IndexRecipeViewModel
    {
        public string Title { get; set; }

        public string CategoryName { get; set; }

        public string ImageUrl { get; set; }    
    }
}

RecipesProject/ViewModels/Recipes/RecipeInListViewModel.cs
namespace RecipesProject.ViewModels.Recipes
{
    public class RecipeInListViewModel
    {
        public int Id { get; set; }

        public string ImageUrl { get; set; } 

        public string Title { get; set; }  

        public int CategoryId { get; set; }

        public string CategoryName { get; set; }    

    }
}

RecipesProject/ViewModels/Recipes/RecipeIngredientInputModel.cs
using System.ComponentModel.DataAnnotations;

namespace RecipesProject.ViewModels.Recipes
{
    public class RecipeIngredientInputModel
    {
        [Required]
        [MinLength(3)]
        public string Name { get; set; }

        [Required]
        [MinLength(1)]
        public string Quantity { get; set; }
    }
}

RecipesProject/ViewModels/Recipes/RecipeIngredientsViewModel.cs
namespace RecipesProject.ViewModels.Recipes
{
    public class RecipeIngredientsViewModel
    {
        public string Name { get; set; }    


        public string Quantity { get; set; }
    }
}

RecipesProject/ViewModels/Recipes/RecipeViewModel.cs
namespace RecipesProject.ViewModels.Recipes
{
    public class RecipeViewModel
    {
        public string Name { get; set; }

        public string CategoryName { get; set; }

        public string AddedByUser { get; set; }

        public string ImageUrl { get; set; }

        public string Description { get; set; }

        public TimeSpan PreparationTime { get; set; }

        public TimeSpan CookingTime { get; set; }

        public int PortionsCount { get; set; }

        public IEnumerable<RecipeIngredientsViewModel> Ingredients { get; set; }
    }
}

RecipesProject/ViewModels/Recipes/RecipesListViewModel.cs
namespace RecipesProject.ViewModels.Recipes
{
    public class RecipesListViewModel
    {
        public IEnumerable<RecipeInListViewModel> Recipes { get; set; }

        public int PageNumber { get; set; }

        public bool HasPreviousPage => this.PageNumber > 1; 

        public bool HasNextPage => this.PageNumber < this.PagesCount;

        public int PreviousPageNumer => this.PageNumber - 1;

        public int NextPageNumber => this.PageNumber + 1;

        public int PagesCount => (int)Math.Ceiling((double)this.RecipesCount / this.ItemsPerPage);    

        public int RecipesCount { get; set; }

        public int ItemsPerPage { get; set; }
    }
}

RecipesProject/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RecipesProject.Services;
using RecipesProject.ViewModels;
using RecipesProject.ViewModels.Recipes;
using System.Diagnostics;

namespace RecipesProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IRecipeService recipeService;

        public HomeController(ILogger<HomeController> logger , IRecipeService recipeService )
        {
            _logger = logger;
            this.recipeService = recipeService;
        }

        public IActionResult Index()
        {
            var indexRecipe = this.recipeService.GetRandom(12);

            return View(indexRecipe);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RecipesProject/Controllers/RecipesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RecipesProject.Services;
using RecipesProject.ViewModels.Recipes;
using System.Security.Claims;

namespace RecipesProject.Controllers
{
    public class RecipesController : Controller
    {
        private readonly ICategoriesService categoriesService;
        private readonly IRecipeService recipeService;
        private readonly IWebHostEnvironment environment;

        public RecipesController(ICategoriesService categoriesService, IRecipeService recipeService , IWebHostEnvironment environment)
        {
            this.categoriesService = categoriesService;
            this.recipeService = recipeService;
            this.environment = environment;
        }

        public async Task<IActionResult> Create()
        {
            var viewmodel = new CreateRecipeInputModel();
            viewmodel.CategoriesItems = this.categoriesService.GetKeyValuePairs();
            return this.View(viewmodel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreateRecipeInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.CategoriesItems = this.categoriesService.GetKeyValuePairs();
                return this.View(input);
            }

            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            try
            {
               await this.recipeService.CreateAsync(input , userId , $"{this.environment.WebRootPath}/photos");
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                input.CategoriesItems = this.categoriesService.GetKeyValuePairs();
                return this.View(input);
            }

            return this.Redirect("/");
        }

        public IActionResult All(int id = 1)
        {
            const int ItemsPerPage = 12;

            var viewModel = new RecipesListViewModel()
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = id,
                RecipesCount = this.recipeService.GetCount(),
                Recipes = this.recipeService.GetAllRecipes(id, 12),
            };

            return this.View(viewModel);
        }

        public IActionResult ById(int id)
        {
            var recipe = this.recipeService.GetById(id);
            return this.View(recipe);
        }

    }
}

RecipesProject/Controllers/ScrapeRecipesController.cs
using Microsoft.AspNetCore.Mvc;
using RecipesProject.Services;

namespace RecipesProject.Controllers
{
    public class ScrapeRecipesController : Controller
    {
        private readonly IGotvachBgScraperService gotvachBgScraperService;

        public ScrapeRecipesController(IGotvachBgScraperService gotvachBgScraperService)
        {
            this.gotvachBgScraperService = gotvachBgScraperService;
        }

        public IActionResult ScrapeRecipe()
        {
            return this.View();
        }

        public async Task<IActionResult> Add()
        {
            await this.gotvachBgScraperService.GetAllRecipesAsync(1193);

            return this.Redirect("/");
        }
    }
}

RecipesProject/Views/Home/Index.cshtml
@model IEnumerable<RecipesProject.ViewModels.Recipes.IndexPageRecipeViewModel>

@{
    ViewData["Title"] = "Home Page";
}

<div class="container mt-4">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-4 mb-4">
                <div class="card h-100" style="width: 100%;">
                    <img class="card-img-top" src="@item.RecipeModel.FirstOrDefault()?.ImageUrl" alt="@item.RecipeModel.FirstOrDefault()?.Title">
                    <div class="card-body">
                        <h5 class="card-title">@item.RecipeModel.FirstOrDefault()?.Title</h5>
                        <p class="card-text">@item.RecipeModel.FirstOrDefault()?.CategoryName</p>
                        <a asp-controller="Recipes" asp-action="ById" asp-route-id="@item.Id" class="btn btn-primary">Go to Recipe</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

RecipesProject/Views/Recipes/All.cshtml
@using RecipesProject.ViewModels.Recipes
@model RecipesListViewModel

@{
    this.ViewData["Title"] = "Всички Рецепти";
}
<div class="container">
    <div class="row">
        @foreach (var recipe in this.Model.Recipes)
        {
            <div class="col-md-3 mb-4">
                <div class="media p-3 border" style="cursor: pointer;" onclick="window.location.href='@Url.Action("ById", "Recipes", new { id = recipe.Id })'">
                    <img class="mr-3" src="@recipe.ImageUrl" alt="" width="250">
                    <div class="media-body">
                        <h5 class="mt-0">@recipe.Title</h5>
                        <p>@recipe.CategoryName</p>
                    </div>
                </div>
            </div>
        }
    </div>
</div>


<nav aria-label="Pagination">
    <ul class="pagination justify-content-center">
        <!-- Previous Button -->
        <li class="page-item @(Model.HasPreviousPage ? "" : "disabled")">
            <a class="page-link" asp-action="All" asp-route-id="@Model.PreviousPageNumer" tabindex="-1">Previous</a>
        </li>

        <!-- Page Numbers Before Current -->
        @for (int i = Model.PageNumber - 3; i < Model.PageNumber; i++)
        {
            if (i > 0)
            {
                <li class="page-item">
                    <a class="page-link" asp-action="All" asp-route-id="@i">@i</a>
                </li>
            }
        }

        <!-- Current Page (Active) -->
        <li class="page-item active">
            <span class="page-link">@Model.PageNumber</span>
        </li>

        <!-- Page Numbers After Current -->
        @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 3; i++)
        {
            if (i <= Model.PagesCount)
            {
                <li class="page-item">
                    <a class="page-link" asp-action="All" asp-route-id="@i">@i</a>
                </li>
            }
        }

        <!-- Next Button -->
        <li class="page-item @(Model.HasNextPage ? "" : "disabled")">
            <a class="page-link" asp-action="All" asp-route-id="@Model.NextPageNumber">Next</a>
        </li>
    </ul>
</nav>

RecipesProject/Views/Recipes/ById.cshtml
@using RecipesProject.ViewModels.Recipes
@model RecipeViewModel

<section class="single-recipe-wrap-layout1 padding-top-74 padding-bottom-50">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 mx-auto">
                <div class="single-recipe-layout1 text-center">
                    <div class="ctg-name">@Model.CategoryName</div>
                    <h2 class="item-title">@Model.Name</h2>

                    <div class="row justify-content-center mb-4">
                        <div class="col-xl-9 col-12"></div>
                        <div class="col-xl-3 col-12">
                            <ul class="action-item d-flex justify-content-center">
                                <li><button><i class="fas fa-print"></i></button></li>
                                <li><button><i class="fas fa-expand-arrows-alt"></i></button></li>
                                <li class="action-share-hover">
                                    <button><i class="fas fa-share-alt"></i></button>
                                    <div class="action-share-wrap">
                                        <a href="#" title="facebook"><i class="fab fa-facebook-f"></i></a>
                                        <a href="#" title="twitter"><i class="fab fa-twitter"></i></a>
                                        <a href="#" title="linkedin"><i class="fab fa-linkedin-in"></i></a>
                                        <a href="#" title="pinterest"><i class="fab fa-pinterest-p"></i></a>
                                        <a href="#" title="skype"><i class="fab fa-skype"></i></a>
                                        <a href="#" title="rss"><i class="fas fa-rss"></i></a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>

                    <div class="item-figure text-center">
                        <img src="@Model.ImageUrl" alt="@Model.Name" class="img-fluid" style="max-width: 80%;">
                    </div>

                    <div class="item-feature">
                        <ul class="d-flex justify-content-center flex-wrap p-0">
                            <li class="px-3 text-center">
                                <div class="feature-wrap">
                                    <div class="media">
                                        <div class="feature-icon"><i class="far fa-clock"></i></div>
                                        <div class="media-body space-sm">
                                            <div class="feature-title">PREP TIME</div>
                                            <div class="feature-sub-title">@Model.PreparationTime.TotalMinutes</div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="px-3 text-center">
                                <div class="feature-wrap">
                                    <div class="media">
                                        <div class="feature-icon"><i class="fas fa-utensils"></i></div>
                                        <div class="media-body space-sm">
                                            <div class="feature-title">COOK TIME</div>
                                            <div class="feature-sub-title">@Model.CookingTime.TotalMinutes</div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="px-3 text-center">
                                <div class="feature-wrap">
                                    <div class="media">
                                        <div class="feature-icon"><i class="fas fa-users"></i></div>
                                        <div class="media-body space-sm">
                                            <div class="feature-title">SERVING</div>
                                            <div class="feature-sub-title">@Model.PortionsCount People</div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="px-3 text-center">
                                <div class="feature-wrap">
                                    <div class="media">
                                        <div class="feature-icon"><i class="far fa-eye"></i></div>
                                        <div class="media-body space-sm">
                                            <div class="feature-title">BY</div>
                                            <div class="feature-sub-title">@Model.AddedByUser</div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>

                    <div class="container mt-4">
                        <div class="row justify-content-center align-items-start gap-4">
                            <div class="col-md-7">
                                <div class="card shadow">
                                    <div class="card-body">
                                        <h3 class="card-title text-center">Description</h3>
                                        <p class="item-description">@Model.Description</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="card shadow">
                                    <div class="card-body">
                                        <h3 class="card-title text-center">Ingredients</h3>
                                        @foreach (var ingredient in Model.Ingredients)
                                        {
                                            <div>
                                                <label>@ingredient.Quantity @ingredient.Name</label>
                                            </div>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>

RecipesProject/Views/Recipes/Create.cshtml
@model RecipesProject.ViewModels.Recipes.CreateRecipeInputModel

@{
    ViewData["Title"] = "Add new recipe";
   // var categoryitems = this.Model.CategoriesItems.Select(x => new SelectListItem(x.Value, x.Key));
}


<form method="post" enctype="multipart/form-data">
  
  <div class="col-md-6 offset-md-3">
        <h1>@ViewData["Title"]</h1>
        <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
             <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control" placeholder="Enter the recipe title"/>
             <span asp-validation-for="Title" class="text-danger"></span>
    </div>

    <div class="form-group">
             <label asp-for="Description"></label>
            <textarea asp-for="Description" class="form-control" rows="5" placeholder="Describe the recipe..."></textarea>
             <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group">
            <label asp-for="PreparationTime"></label>
            <input asp-for="PreparationTime" class="form-control" placeholder="e.g., 20"/>
            <span asp-validation-for="PreparationTime" class="text-danger"></span>
    </div>

    <div class="form-group">
            <label asp-for="CookingTime"></label>
            <input asp-for="CookingTime" class="form-control" placeholder="e.g., 40"/>
            <span asp-validation-for="CookingTime" class="text-danger"></span>
    </div>

    <div class="form-group">
            <label asp-for="PortionsCount"></label>
            <input asp-for="PortionsCount" class="form-control" placeholder="e.g., 4"/>
            <span asp-validation-for="PortionsCount" class="text-danger"></span>
    </div>
    <div class="form-group">
            <label asp-for="CategoryId"></label>
            <select asp-for="CategoryId" class="form-control" asp-items="@Model.CategoriesItems" ></select>
            <span asp-validation-for="CategoryId" class="text-danger"></span>
    </div>

    <div class="form-group">
            <label asp-for="Photo"></label>
            <input asp-for="Photo" class="form-control" />
            <span asp-validation-for="Photo" class="text-danger"></span>
    </div>
        
        <hr />
    <div id="ingredientsContainer" class="form-group mb-3>
           <label asp-for="Ingredients"></label>
           <button id="addIngredientButton" type="button" class="btn btn-outline-primary btn-sm mb-3">Add Ingredients</button>
    </div>
        <hr />
        <div class="text-center mt-4">
            <button type="submit" class="btn btn-primary btn-lg">Submit</button>
        </div>
  </div>

</form>


 
    <script>
         document.getElementById('addIngredientButton').addEventListener('click', function () {
        const container = document.getElementById('ingredientsContainer');


        const fieldGroup = document.createElement('div');
        fieldGroup.className = 'ingredient-group mb-3';


        const nameField = document.createElement('input');
        nameField.type = 'text';
        nameField.placeholder = 'Ingredient Name';
        nameField.className = 'form-control mb-2';


        const quantityField = document.createElement('input');
        quantityField.type = 'text';
        quantityField.placeholder = 'Quantity';
        quantityField.className = 'form-control mb-2';


        fieldGroup.appendChild(nameField);
        fieldGroup.appendChild(quantityField);

        container.appendChild(fieldGroup);

        updateIngredientFieldNames();
    });

       function updateIngredientFieldNames() {
        const ingredientGroups = document.querySelectorAll('.ingredient-group');
        ingredientGroups.forEach((group, index) => {

            const nameField = group.querySelector('input:nth-of-type(1)');
            const quantityField = group.querySelector('input:nth-of-type(2)');
            
            if (nameField && quantityField) {
                nameField.name = `Ingredients[${index}].Name`;
                quantityField.name = `Ingredients[${index}].Quantity`;
            }
        });
       }

    </script>

RecipesProject/Views/ScrapeRecipes/ScrapeRecipe.cshtml
@{
    ViewData["Title"] = "ScrapeRecipe";
}

<div class="text-center">
   <a class="button" asp-asp-controller="ScrapeRecipes" asp-action="Add"> Add Data </a>
</div>

RecipesProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RecipesProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/style.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RecipesProject.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/recipe.css/" asp-append-version="true">

</head>
<body>
    <div id="wrapper" class="wrapper">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RecipesProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Recipes" asp-action="All">Рецепти</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Recipes" asp-action="Create">Create recipe </a>                
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    </div>
    <footer class="ranna-bg-dark">
        <div class="container">
            &copy; 2024 - RecipesProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="/_framework/aspnetcore-browser-refresh.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>